# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release
on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew runPluginVerifier
      - name: Artifacts Upload
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/distributions
      - name: Set change log
        id: changelog
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          ./gradlew getChangelog --console=plain -q --no-header --unreleased >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Set version
        id: version
        run: |
          echo 'VERSION<<EOF' >> $GITHUB_ENV
          ./gradlew printVersion --console=plain -q >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: {{env.CHANGELOG}}
          draft: true
          prerelease: false
    #- name: Build with Gradle
    #  run: ./gradlew publishPlugin -Pjb_token=${{ secrets.JB_TOKEN }}
